Dex:
  target: dev
  outputs:
    dev:
      dbname: envio-dev
      host: envio-postgres
      pass: testing
      port: 5432
      schema: envio_dev
      threads: 4
      type: postgres
      user: postgres
      # sslmode: disable

    prod:
      dbname: "{{ env_var('PROD_DB_NAME') }}"
      host: "{{ env_var('ENVIO_PG_HOST') }}"
      pass: "{{ env_var('ENVIO_PG_PASSWORD') }}"
      port: "{{ env_var('ENVIO_PG_PORT') | int }}"
      schema: envio_prod
      threads: 4
      type: postgres
      user: "{{ env_var('ENVIO_PG_USER') }}"
      sslmode: require
